apiVersion: v1
kind: Secret
metadata:
  name: azure-mysql-secret
  namespace: hospital-system
  labels:
    app: hospital-backend
    database: azure-mysql
type: Opaque
data:
  DB_HOST: bXktZGIubXlzcWwuZGF0YWJhc2UuYXp1cmUuY29t
  DB_USER: bWFub2o=
  DB_PASSWORD: Q2hhd2FrdWxhQDAxMTM=
  DB_NAME: bXlfZGI=